version: '3'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8.1-fpm-alpine
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker-config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./docker-config/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    db:
        image: mysql:latest
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3317:3306"
        environment:
            MYSQL_DATABASE: innoscripta
            MYSQL_ROOT_PASSWORD: innoscriptapass1
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker-config/init:/docker-entrypoint-initdb.d
            - ./docker-config/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network
    redis:
        image: 'redis:alpine'
        container_name: redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'dbdata:/var/lib/redis'
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
volumes:
    dbdata:
        driver: local
